from numpy import random
from matplotlib import pyplot as plt
import numpy as np
from matplotlib.pyplot import figure

# Code to make CDF from P_Y_N(.) for each given N
np.random.seed(1000)        # Using 1000 as seed

def inverse_CDF(x):         #calculating inverse cdf of x
        if(x == 1/2):
            return 0
        elif(x > 1/2):
            return np.sqrt(2*(x - 1/2))
        else:
            return -np.sqrt(2*(1/2 - x))

def random_number_generator():      #the number generator from previous problem
    p = np.random.uniform(0,1)
    return inverse_CDF(p)

def random_normal_generator(n):     #random number generator for P_Y_N(.)
    data = []
    for j in range(n):
        data.append(random_number_generator())
    return sum(data) / len(data)

N = [1,2,4,8,16,32,64]              #value of N used in P_Y_N(.)
total_numbers = 10**4              #Number of values generated by this code.

for i in N:                         #creating the list result which stores 10**4 random numbers
    result = []
    for j in range(total_numbers):
        result.append(random_normal_generator(i))       #using random_normal_generator to create the values and storing it in result 
    #the below code plots the cdf.
    plt.rcParams["figure.figsize"] = [7.50, 6]
    plt.rcParams["figure.autolayout"] = True
    count, bins_count = np.histogram(result, bins=200)
    pdf = count/np.sum(count)
    cdf = np.cumsum(pdf)
    plt.plot(bins_count[1:], cdf, label="CDF , N = " + str(i))
    plt.legend()
plt.title("CDF for different values of N")
plt.xlabel('x')
plt.ylabel("$f_X(x)$")
plt.show()  